# Viral Metagenomic Assembly Toolkit Configuration
# Copy this file to config.yaml and modify for your specific setup

# General Settings
project_name: "virome_assembly_project"
output_base_dir: "results"
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR

# Input Data Configuration
input:
  # Directory containing cleaned paired-end reads
  reads_directory: "data/cleaned_reads"
  
  # Sample metadata file (CSV format)
  metadata_file: "examples/metadata_template.csv"
  
  # File naming pattern for paired-end reads
  # Use {sample} as placeholder for sample name
  read_pattern:
    r1: "{sample}_R1.fastq.gz"
    r2: "{sample}_R2.fastq.gz"

# Computational Resources
resources:
  # Number of CPU threads for parallel processing
  threads: 8
  
  # Memory allocation (GB)
  memory_gb: 32
  
  # Maximum number of parallel jobs
  max_parallel_jobs: 4
  
  # Temporary directory for large files
  temp_dir: "/tmp"

# K-mer Analysis Configuration
kmer_analysis:
  # K-mer size for Sourmash sketching
  kmer_size: 31
  
  # Sketch size (number of hashes)
  sketch_size: 10000
  
  # Similarity threshold for co-assembly grouping
  similarity_threshold: 0.8
  
  # Maximum group size for co-assemblies
  max_group_size: 8

# Variable Analysis Configuration  
variable_analysis:
  # Minimum R-squared threshold for important variables
  min_r_squared: 0.1
  
  # P-value threshold for significance
  p_value_threshold: 0.05
  
  # Number of permutations for PERMANOVA
  permutations: 999

# Assembly Configuration
assembly:
  # Assemblers to use (megahit, metaspades, or both)
  assemblers: ["megahit", "metaspades"]
  
  # Minimum contig length
  min_contig_length: 500
  
  # Assembly strategies to execute
  strategies:
    individual: true
    strategic_coassembly: true
    global_coassembly: true
    meta_assembly: true
  
  # Assembler-specific settings
  megahit:
    presets: "meta-sensitive"
    min_count: 2
    k_list: "21,29,39,59,79,99,119,141"
  
  metaspades:
    k_list: "21,33,55,77"
    careful: true

# Quality Assessment Configuration
quality_assessment:
  # CheckV database path (update to your installation)
  checkv_database: "/opt/checkv-db-v1.5"
  
  # Minimum contig length for CheckV analysis
  min_contig_length_checkv: 1000
  
  # Read mapping settings
  mapping:
    # Minimum mapping quality
    min_mapq: 10
    
    # Aligner to use (bwa or bowtie2)
    aligner: "bwa"
  
  # Coverage analysis thresholds
  coverage_thresholds:
    low_coverage: 5.0
    low_breadth: 50.0
    low_mapping: 30.0

# Database Paths
databases:
  # CheckV database (for viral genome quality assessment)
  checkv: "/opt/checkv-db-v1.5"
  
  # Host reference genome (for contamination filtering)
  host_reference: "/opt/references/human_genome/GRCh38.fa"
  
  # Adapter sequences file
  adapters: "/opt/adapters/TruSeq3-PE.fa"

# Output Configuration
output:
  # Keep intermediate files
  keep_intermediate: false
  
  # Compress output files
  compress_outputs: true
  
  # Generate detailed logs
  verbose_logging: true
  
  # Create backup of important results
  backup_results: true

# Pipeline Execution
pipeline:
  # Force re-run of completed steps
  force_rerun: false
  
  # Resume from last checkpoint
  resume: true
  
  # Maximum runtime per step (hours)
  max_runtime_hours: 24
  
  # Email notifications (requires system mail setup)
  email_notifications:
    enabled: false
    recipient: "user@institution.edu"
    smtp_server: "smtp.institution.edu"

# Advanced Settings
advanced:
  # Enable experimental features
  experimental_features: false
  
  # Custom script paths
  custom_scripts:
    preprocessing: null
    postprocessing: null
  
  # Additional quality filters
  quality_filters:
    min_gc_content: 20.0
    max_gc_content: 80.0
    max_n_content: 10.0
  
  # Performance monitoring
  monitoring:
    track_memory_usage: true
    track_runtime: true
    generate_performance_report: true

# Software Versions (for reproducibility)
software_versions:
  sourmash: "4.8.0"
  megahit: "1.2.9"
  metaspades: "3.15.5"
  checkv: "1.0.1"
  bwa: "0.7.17"
  samtools: "1.17"
  bedtools: "2.31.0"
  seqtk: "1.3"
  python: "3.9.0"
  r: "4.3.0"